language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
 allow_failures:
 fast_finish: true
 include:
 - php: 7.0
   env: DB=mysqli
 - php: 7.0
   env: DB=pgsql
   addons:
      postgresql: 9.3
 - php: 7.1
   env: DB=mysqli
 - php: 7.1
   env: DB=pgsql
   addons:
      postgresql: 9.3
env:
 global:
  - MOODLE_BRANCH=master
  - IGNORE_PATHS=amd/build,amd/src/bootstrap.js,amd/src/icon_system_fontawesome.js,javascript/html5shiv.js,javascript/syntaxhighlighter_3_0_83/
  # Ignore custom.css until CSSlint can be instructed to ignore lines for '[[setting:customcss]]'.
  - IGNORE_NAMES=*.txt,custom.css,font.css,font-awesome.css

before_install:
# This disables XDebug which should speed up the build.  One reason to remove this
# line is if you are trying to generate code coverage with PHPUnit.
  - phpenv config-rm xdebug.ini
# Currently we are inside of the clone of your repository.  We move up two
# directories to build the project.
  - cd ../..
# Update Composer.
  - composer selfupdate
# Install this project into a directory called "ci".
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
# Update the $PATH so scripts from this project can be called easily.
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
